ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "roomNumberStart" INTEGER;
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "roomNumberEnd" INTEGER;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "allocatedRoomNumber" INTEGER;
